/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventoryFilamentsRouteImport } from './routes/inventory/filaments'
import { Route as InventorySuppliesRouteImport } from './routes/inventory/supplies'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as InventoryProductsIndexRouteImport } from './routes/inventory/products/index'
import { Route as InventoryProductsProductIdRouteImport } from './routes/inventory/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryFilamentsRoute = InventoryFilamentsRouteImport.update({
  id: '/inventory/filaments',
  path: '/inventory/filaments',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySuppliesRoute = InventorySuppliesRouteImport.update({
  id: '/inventory/supplies',
  path: '/inventory/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsIndexRoute = InventoryProductsIndexRouteImport.update({
  id: '/inventory/products/',
  path: '/inventory/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsProductIdRoute =
  InventoryProductsProductIdRouteImport.update({
    id: '/inventory/products/$productId',
    path: '/inventory/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/finances': typeof FinancesRoute
  '/inventory/filaments': typeof InventoryFilamentsRoute
  '/inventory/supplies': typeof InventorySuppliesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/inventory/products/$productId': typeof InventoryProductsProductIdRoute
  '/inventory/products/': typeof InventoryProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/finances': typeof FinancesRoute
  '/inventory/filaments': typeof InventoryFilamentsRoute
  '/inventory/supplies': typeof InventorySuppliesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/inventory/products/$productId': typeof InventoryProductsProductIdRoute
  '/inventory/products': typeof InventoryProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/finances': typeof FinancesRoute
  '/inventory/filaments': typeof InventoryFilamentsRoute
  '/inventory/supplies': typeof InventorySuppliesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/inventory/products/$productId': typeof InventoryProductsProductIdRoute
  '/inventory/products/': typeof InventoryProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/finances'
    | '/inventory/filaments'
    | '/inventory/supplies'
    | '/orders/$orderId'
    | '/inventory/'
    | '/orders/'
    | '/inventory/products/$productId'
    | '/inventory/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/finances'
    | '/inventory/filaments'
    | '/inventory/supplies'
    | '/orders/$orderId'
    | '/inventory'
    | '/orders'
    | '/inventory/products/$productId'
    | '/inventory/products'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/finances'
    | '/inventory/filaments'
    | '/inventory/supplies'
    | '/orders/$orderId'
    | '/inventory/'
    | '/orders/'
    | '/inventory/products/$productId'
    | '/inventory/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  FinancesRoute: typeof FinancesRoute
  InventoryFilamentsRoute: typeof InventoryFilamentsRoute
  InventorySuppliesRoute: typeof InventorySuppliesRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  InventoryProductsProductIdRoute: typeof InventoryProductsProductIdRoute
  InventoryProductsIndexRoute: typeof InventoryProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/filaments': {
      id: '/inventory/filaments'
      path: '/inventory/filaments'
      fullPath: '/inventory/filaments'
      preLoaderRoute: typeof InventoryFilamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/supplies': {
      id: '/inventory/supplies'
      path: '/inventory/supplies'
      fullPath: '/inventory/supplies'
      preLoaderRoute: typeof InventorySuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products/': {
      id: '/inventory/products/'
      path: '/inventory/products'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof InventoryProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products/$productId': {
      id: '/inventory/products/$productId'
      path: '/inventory/products/$productId'
      fullPath: '/inventory/products/$productId'
      preLoaderRoute: typeof InventoryProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  FinancesRoute: FinancesRoute,
  InventoryFilamentsRoute: InventoryFilamentsRoute,
  InventorySuppliesRoute: InventorySuppliesRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  InventoryProductsProductIdRoute: InventoryProductsProductIdRoute,
  InventoryProductsIndexRoute: InventoryProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
